### ISSUE TITLE
Add CI option

### ISSUE THREAD

**Issue by thec00n** [ConsenSys/truffle-security#106]
It be great to be able run truffle-security in a Continuous Integration setup such as CircleCI. A user could run a full analysis as a separate CI step, e.g. 

`truffle run verify --ci --fail-on=High`

In the above example truffle-security runs the full analysis and checks if there are any High severity findings present in the analysis report and if so exits with 1 and prints the issues that failed the step to the console. truffle-security should also allow a user to set the `--fail-on` with the severity ratings Medium and Low.

**Comment by rocky** [comment]
Having MythX-enabled CI has long been in the plan, we may even have gitcoin bounties for this as part of the upcoming Ethereal Summit. 

But this really isn't about truffle per se. it would be about _any_ Solidity file. 

If it happens to be in truffle and we can capture that, all the better. But it could be part of a VSCode project which uses just a different way to organize solidity files. Or it could be github project which is neither a VSCode nor a truffle project. 

It so happens that  whichever kind of format the file or project is in, this CI think if based off of this code (which is likely) will truffle _libraries_  as this does, but that's just because they do a bit of what is needed to be done, rather than because truffle is intended to be used by the smart contract developer. 

And down the plan is then to extract what is here, extend as necessary and put this in an independent library, or as some folks prefer to call it, an SDK. 

But sure, until such a project and library is written, we can keep this open here until we have a better place to note this in a public fashion. 

And I guess it serves to remind, that the CI solution should should also handle truffle projects as well.

**Comment by tagomaru** [comment]
> truffle run verify --ci --fail-on=High

My idea to implement it quickly is like below.

1. --fail-on option should be independent from CI. Maybe the value is either warning or error now.
2. Output some files (ex. json) regarding 'Internal MythX errors encountered:' and problems (means security issues). CI can check them after running truffle-security to find some error like timeout and security issues.

Do you think it makes sense?

**Comment by rocky** [comment]
For CI kinds of things it makes more sense to have things directed through a configuration file, similar to eslint's `.eslintrc`,  our a circleci.yaml that controls Ci works and what kinds of warnings to give.  

And perhaps this configuration then can be used whether or not CI was used. For example the configuration may be used to indicate that you don't want to hear about "floating pragmas" as well as these threshhold kinds of things. 

More generally speaking we need to have a broader discussion of how to do CI in general. In this specific situation, I am not in favor of let's make this hack here and see where it gets us. 

Here is a little analogy that I offer for amusement. If you are pressed for time, you can skip the rest of and just go with the above if you don't want a story.

In sailing there are two kinds of navigation, one with a map and navigation tools and one called "line of site". When you have a map which indicates things like where sandbars are and where the channel is and how strong the current is, you may decide that in order to go from here to there you have to go not in the straight path but vary a little bit, and based on the wind you may tack back and forth. So you are not going the most direct route, but that's okay because you have an overall plan. 

In line of site you don't have these important details but just say: hey there's another island over there and that seems closer so let's get to that. And so on. In this approach you may find out eventually that there is a sand bar between where you wind up and where you need to get to. Or maybe there a strong current and you are on the wrong direction of that, but if you had gone a different route maybe you'd be on the right side of the current.  

What we are doing here feels like line of site. What I'd prefer is having a map which lays out all of the issues.

**Comment by tagomaru** [comment]
@rocky 
Thx for your comment.
ok i understand your thoughts. Keep discussing about how we can improve with CI.

**Comment by rocky** [comment]
This is covered by #35 and #118
